services:
  - type: web
    name: agrismart-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DATABASE_URL
        fromSecret: database_url
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /
    port: 8000
